name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        check-latest: true
        cache: true
        cache-dependency-path: go.sum
        
    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh
      
    - name: Zip the Build
      run: |
        mkdir asset
        zip -r asset/ScanRepeat.zip ./output/*
        VERSION_TAG=${{ github.ref }
        VERSION_TAG=${VERSION_TAG#*refs/tags/}
      
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ env.VERSION_TAG }}
        name: Release ${{ env.VERSION_TAG }}
        body: TODO New Release.
        draft: false
        prerelease: false
        token: ${{ secrets.UPLOAD_TOKEN }}
        files: |
          asset/ScanRepeat.zip
